import type {
  User, Municipio, School, Turma, Student, Trimester,
  Evaluation, TeacherEvaluation, SecretaryFeedback, Training,
  Evidence, SwotAnalysis, SmartGoal, ActionPlan, DashboardStats,
  ProjectConfig, ChartDataPoint,
} from './types';

// ── Projeto ─────────────────────────────────────────────────
export const projectConfig: ProjectConfig = {
  projectName: 'Eleva+ Educação Empreendedora',
  networkName: 'Rede Municipal de Ensino de Limoeiro de Anadia',
  year: 2025,
  executionPeriod: 'Fevereiro a Novembro de 2025',
  company: 'Acelera+ Escola de Empreendedorismo',
  coordinator: 'Profa. Dra. Mariana Costa',
  description:
    'Projeto de Educação Empreendedora para desenvolvimento de competências do século XXI nas escolas municipais de Limoeiro de Anadia, Alagoas — em alinhamento com as metas do IDEB municipal e as diretrizes da Secretaria Municipal de Educação.',
  objectives: [
    'Desenvolver competências empreendedoras nos estudantes',
    'Capacitar docentes para metodologia ativa',
    'Fortalecer cultura de inovação nas escolas',
    'Produzir dados pedagógicos estratégicos para a Secretaria',
    'Contribuir para a elevação do IDEB municipal (meta: 7,0 nos anos finais)',
  ],
  segments: ['Ensino Fundamental I', 'Ensino Fundamental II'],
  series: ['4º ano', '5º ano', '6º ano', '7º ano', '8º ano', '9º ano'],
  estimatedStudents: 1200,
  estimatedTeachers: 52,
  estimatedSchools: 5,
};

// ── Usuário atual (simulado) ─────────────────────────────────
export const currentUser: User = {
  id: 'u001',
  name: 'Ana Paula Rodrigues',
  email: 'ana.rodrigues@elevaplus.edu.br',
  phone: '(82) 98765-4321',
  role: 'super_admin',
  municipio: 'Limoeiro de Anadia',
  status: 'ativo',
  lastAccess: '2025-06-04T09:30:00',
};

// ── Município ────────────────────────────────────────────────
// Fonte: QEdu / Censo Escolar INEP 2025 — Limoeiro de Anadia, AL
export const municipios: Municipio[] = [
  {
    id: 'm001',
    name: 'Limoeiro de Anadia',
    state: 'AL',
    secretario: 'Sec. Mun. Francisco das Chagas',
    schools: 25, // total rede municipal — Censo INEP 2025
  },
];

// ── Escolas ──────────────────────────────────────────────────
// Fonte: Censo Escolar INEP 2025 — Rede Municipal de Limoeiro de Anadia, AL (25 unidades)
// s001–s005: EMEBs participantes do projeto Eleva+ (ensino fundamental)
// s006–s025: demais unidades da rede (CEI, CMEI e EMEBs não-projeto)
export const schools: School[] = [
  // ── 5 EMEBs participantes do projeto ────────────────────────
  {
    id: 's001',
    name: 'EMEB Presidente Ernesto Geisel',
    code: 'LA-001',
    municipioId: 'm001',
    address: 'Rua Principal, s/n — Centro, Limoeiro de Anadia — AL',
    gestorName: 'Francisca Nunes Cavalcante',
    email: 'ernestogeisel@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1201',
    classCount: 10,
    studentCount: 287,
    teacherCount: 14,
    status: 'ativo',
    participationRate: 94,
    avgScore: 7.2,
    elevaIndex: 87,
    observations: 'Maior EMEB da sede — destaque em participação.',
  },
  {
    id: 's002',
    name: 'EMEB Coronel Adauto Gomes Barbosa',
    code: 'LA-002',
    municipioId: 'm001',
    address: 'Av. Coronel Adauto, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Roberto Campos dos Santos',
    email: 'coroladauto@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1202',
    classCount: 8,
    studentCount: 242,
    teacherCount: 13,
    status: 'ativo',
    participationRate: 96,
    avgScore: 7.5,
    elevaIndex: 91,
    observations: 'Maior índice Eleva+ da rede.',
  },
  {
    id: 's003',
    name: 'EMEB Pedro Ribeiro',
    code: 'LA-003',
    municipioId: 'm001',
    address: 'Travessa Pedro Ribeiro, s/n — Zona Rural, Limoeiro de Anadia — AL',
    gestorName: 'Carla Mendes Ferreira',
    email: 'pedroribeiro@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1203',
    classCount: 7,
    studentCount: 174,
    teacherCount: 10,
    status: 'ativo',
    participationRate: 72,
    avgScore: 5.8,
    elevaIndex: 62,
    observations: 'Escola rural — desafio de conectividade.',
  },
  {
    id: 's004',
    name: 'EMEB João de Deus Barbosa',
    code: 'LA-004',
    municipioId: 'm001',
    address: 'Rua João de Deus, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Marcelo Souza Lima',
    email: 'joaodedeus@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1204',
    classCount: 9,
    studentCount: 198,
    teacherCount: 11,
    status: 'ativo',
    participationRate: 88,
    avgScore: 6.8,
    elevaIndex: 74,
  },
  {
    id: 's005',
    name: 'EMEB Araci Cavalcante da Silva',
    code: 'LA-005',
    municipioId: 'm001',
    address: 'Rua Araci Cavalcante, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Lúcia Ferreira Barros',
    email: 'aracicavalcante@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1205',
    classCount: 6,
    studentCount: 155,
    teacherCount: 9,
    status: 'ativo',
    participationRate: 81,
    avgScore: 6.5,
    elevaIndex: 70,
  },

  // ── Demais unidades da rede municipal ────────────────────────
  {
    id: 's006',
    name: 'CAEE Profª Divaneuza Clarindo Duarte',
    code: 'LA-006',
    municipioId: 'm001',
    address: 'Rua das Palmeiras, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Ana Lúcia Torres',
    email: 'caee@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1206',
    classCount: 4,
    studentCount: 68,
    teacherCount: 8,
    status: 'ativo',
    participationRate: 100,
    avgScore: 0,
    elevaIndex: 0,
    observations: 'Centro de Atendimento Educacional Especializado — AEE.',
  },
  {
    id: 's007',
    name: 'CEI Jorge Possidonio dos Reis',
    code: 'LA-007',
    municipioId: 'm001',
    address: 'Rua Jorge Possidonio, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Rosângela Melo',
    email: 'ceijorge@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1207',
    classCount: 5,
    studentCount: 92,
    teacherCount: 6,
    status: 'ativo',
    participationRate: 0,
    avgScore: 0,
    elevaIndex: 0,
    observations: 'Educação Infantil.',
  },
  {
    id: 's008',
    name: 'CEI Luzinete Maria da Conceição',
    code: 'LA-008',
    municipioId: 'm001',
    address: 'Rua das Acácias, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Silvana Ferreira',
    email: 'ceiluzinete@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1208',
    classCount: 4,
    studentCount: 78,
    teacherCount: 5,
    status: 'ativo',
    participationRate: 0,
    avgScore: 0,
    elevaIndex: 0,
    observations: 'Educação Infantil.',
  },
  {
    id: 's009',
    name: 'CMEI Edite Barbosa de Almeida',
    code: 'LA-009',
    municipioId: 'm001',
    address: 'Rua Edite Barbosa, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Conceição Lima',
    email: 'cmeiedite@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1209',
    classCount: 4,
    studentCount: 84,
    teacherCount: 5,
    status: 'ativo',
    participationRate: 0,
    avgScore: 0,
    elevaIndex: 0,
    observations: 'Educação Infantil.',
  },
  {
    id: 's010',
    name: 'CMEI Marina Soares Barbosa',
    code: 'LA-010',
    municipioId: 'm001',
    address: 'Av. Marina Soares, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Tereza Cavalcante',
    email: 'cmeimarina@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1210',
    classCount: 5,
    studentCount: 96,
    teacherCount: 6,
    status: 'ativo',
    participationRate: 0,
    avgScore: 0,
    elevaIndex: 0,
    observations: 'Educação Infantil.',
  },
  {
    id: 's011',
    name: 'CMEI Nizete Barbosa da Silva Faustino',
    code: 'LA-011',
    municipioId: 'm001',
    address: 'Rua Nizete Barbosa, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Dalva Santos',
    email: 'cmeinizte@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1211',
    classCount: 4,
    studentCount: 72,
    teacherCount: 5,
    status: 'ativo',
    participationRate: 0,
    avgScore: 0,
    elevaIndex: 0,
    observations: 'Educação Infantil.',
  },
  {
    id: 's012',
    name: 'EMEB Benedito Galdino da Silva',
    code: 'LA-012',
    municipioId: 'm001',
    address: 'Rua Benedito Galdino, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Jorge Ferreira Neto',
    email: 'beneditogaldino@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1212',
    classCount: 6,
    studentCount: 148,
    teacherCount: 9,
    status: 'ativo',
    participationRate: 78,
    avgScore: 6.1,
    elevaIndex: 58,
  },
  {
    id: 's013',
    name: 'EMEB Izabel Ferreira Boia',
    code: 'LA-013',
    municipioId: 'm001',
    address: 'Rua Izabel Ferreira, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Maria das Dores Lima',
    email: 'izabelboia@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1213',
    classCount: 5,
    studentCount: 132,
    teacherCount: 8,
    status: 'ativo',
    participationRate: 75,
    avgScore: 6.3,
    elevaIndex: 60,
  },
  {
    id: 's014',
    name: 'EMEB José Teodoro da Silva',
    code: 'LA-014',
    municipioId: 'm001',
    address: 'Sítio José Teodoro, s/n — Zona Rural, Limoeiro de Anadia — AL',
    gestorName: 'Antônio Carlos Melo',
    email: 'joseTeodoro@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1214',
    classCount: 4,
    studentCount: 96,
    teacherCount: 6,
    status: 'ativo',
    participationRate: 68,
    avgScore: 5.7,
    elevaIndex: 52,
    observations: 'Escola rural multisseriada.',
  },
  {
    id: 's015',
    name: 'EMEB Maria Ferreira de Almeida',
    code: 'LA-015',
    municipioId: 'm001',
    address: 'Rua Maria Ferreira, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Edilene Barros',
    email: 'mariaferreira@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1215',
    classCount: 5,
    studentCount: 118,
    teacherCount: 7,
    status: 'ativo',
    participationRate: 80,
    avgScore: 6.4,
    elevaIndex: 62,
  },
  {
    id: 's016',
    name: 'EMEB Maria Julia Ferreira de Albuquerque',
    code: 'LA-016',
    municipioId: 'm001',
    address: 'Rua Maria Julia, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Sueli Cavalcante',
    email: 'mariajulia@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1216',
    classCount: 5,
    studentCount: 124,
    teacherCount: 7,
    status: 'ativo',
    participationRate: 76,
    avgScore: 6.2,
    elevaIndex: 59,
  },
  {
    id: 's017',
    name: 'EMEB Maria Lima da Conceição',
    code: 'LA-017',
    municipioId: 'm001',
    address: 'Rua Maria Lima, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Joselita Santos',
    email: 'marialima@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1217',
    classCount: 5,
    studentCount: 110,
    teacherCount: 7,
    status: 'ativo',
    participationRate: 82,
    avgScore: 6.5,
    elevaIndex: 63,
  },
  {
    id: 's018',
    name: 'EMEB Nossa Senhora da Conceição',
    code: 'LA-018',
    municipioId: 'm001',
    address: 'Praça Nossa Senhora, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Fátima Rodrigues',
    email: 'nossasenhoraconceicao@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1218',
    classCount: 7,
    studentCount: 163,
    teacherCount: 10,
    status: 'ativo',
    participationRate: 85,
    avgScore: 6.7,
    elevaIndex: 68,
  },
  {
    id: 's019',
    name: 'EMEB Olival Tenorio Costa Neto',
    code: 'LA-019',
    municipioId: 'm001',
    address: 'Rua Olival Tenório, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Valdemar Gomes',
    email: 'olivaltenorio@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1219',
    classCount: 6,
    studentCount: 141,
    teacherCount: 9,
    status: 'ativo',
    participationRate: 79,
    avgScore: 6.3,
    elevaIndex: 61,
  },
  {
    id: 's020',
    name: 'EMEB Pedro Antonio Lino',
    code: 'LA-020',
    municipioId: 'm001',
    address: 'Estrada Pedro Antônio, s/n — Zona Rural, Limoeiro de Anadia — AL',
    gestorName: 'Eliana Ferraz',
    email: 'pedroantonio@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1220',
    classCount: 4,
    studentCount: 88,
    teacherCount: 6,
    status: 'ativo',
    participationRate: 70,
    avgScore: 5.9,
    elevaIndex: 55,
    observations: 'Escola rural.',
  },
  {
    id: 's021',
    name: 'EMEB Pedro Araújo dos Santos',
    code: 'LA-021',
    municipioId: 'm001',
    address: 'Rua Pedro Araújo, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Cícero Almeida',
    email: 'pedroaraujo@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1221',
    classCount: 5,
    studentCount: 115,
    teacherCount: 7,
    status: 'ativo',
    participationRate: 77,
    avgScore: 6.2,
    elevaIndex: 60,
  },
  {
    id: 's022',
    name: 'EMEB Prefeito Benicio Ferreira Reis',
    code: 'LA-022',
    municipioId: 'm001',
    address: 'Rua Benício Ferreira, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Graça Monteiro',
    email: 'prefeitobenicio@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1222',
    classCount: 6,
    studentCount: 137,
    teacherCount: 8,
    status: 'ativo',
    participationRate: 83,
    avgScore: 6.6,
    elevaIndex: 65,
  },
  {
    id: 's023',
    name: 'EMEB Prefeito Pedro Ferreira da Silva',
    code: 'LA-023',
    municipioId: 'm001',
    address: 'Rua Prefeito Pedro Ferreira, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Nivaldo Barros',
    email: 'prefeitopedro@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1223',
    classCount: 5,
    studentCount: 122,
    teacherCount: 7,
    status: 'ativo',
    participationRate: 74,
    avgScore: 6.1,
    elevaIndex: 57,
  },
  {
    id: 's024',
    name: 'EMEB Rodrigo da Rocha Cavalcante Camelo',
    code: 'LA-024',
    municipioId: 'm001',
    address: 'Sítio Rodrigo Camelo, s/n — Zona Rural, Limoeiro de Anadia — AL',
    gestorName: 'Raimundo Costa',
    email: 'rodrigocamelo@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1224',
    classCount: 4,
    studentCount: 94,
    teacherCount: 6,
    status: 'ativo',
    participationRate: 69,
    avgScore: 5.6,
    elevaIndex: 51,
    observations: 'Escola rural.',
  },
  {
    id: 's025',
    name: 'EMEB Rosalia Ferreira Reis',
    code: 'LA-025',
    municipioId: 'm001',
    address: 'Rua Rosália Ferreira, s/n — Limoeiro de Anadia — AL',
    gestorName: 'Marinalva Pereira',
    email: 'rosaliaferreirareis@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1225',
    classCount: 5,
    studentCount: 128,
    teacherCount: 8,
    status: 'ativo',
    participationRate: 81,
    avgScore: 6.4,
    elevaIndex: 64,
  },
];

// ── Turmas ───────────────────────────────────────────────────
export const turmas: Turma[] = [
  { id: 't001', name: '6º A', schoolId: 's001', schoolName: 'EMEB Presidente Ernesto Geisel', serie: '6º ano', turno: 'manhã', teacherId: 'p001', teacherName: 'Prof. Lucas Andrade', studentCount: 28, trimestre: '2º Trimestre', participationStatus: 'alta', avgScore: 7.4 },
  { id: 't002', name: '6º B', schoolId: 's001', schoolName: 'EMEB Presidente Ernesto Geisel', serie: '6º ano', turno: 'tarde', teacherId: 'p002', teacherName: 'Profa. Beatriz Lima', studentCount: 26, trimestre: '2º Trimestre', participationStatus: 'alta', avgScore: 7.1 },
  { id: 't003', name: '7º A', schoolId: 's001', schoolName: 'EMEB Presidente Ernesto Geisel', serie: '7º ano', turno: 'manhã', teacherId: 'p003', teacherName: 'Prof. Fernando Dias', studentCount: 30, trimestre: '2º Trimestre', participationStatus: 'media', avgScore: 6.8 },
  { id: 't004', name: '8º A', schoolId: 's002', schoolName: 'EMEB Coronel Adauto Gomes Barbosa', serie: '8º ano', turno: 'manhã', teacherId: 'p004', teacherName: 'Profa. Camila Torres', studentCount: 32, trimestre: '2º Trimestre', participationStatus: 'alta', avgScore: 7.0 },
  { id: 't005', name: '5º A', schoolId: 's002', schoolName: 'EMEB Coronel Adauto Gomes Barbosa', serie: '5º ano', turno: 'tarde', teacherId: 'p005', teacherName: 'Prof. Diego Melo', studentCount: 25, trimestre: '2º Trimestre', participationStatus: 'media', avgScore: 6.4 },
  { id: 't006', name: '9º A', schoolId: 's003', schoolName: 'EMEB Pedro Ribeiro', serie: '9º ano', turno: 'manhã', teacherId: 'p006', teacherName: 'Profa. Juliana Costa', studentCount: 29, trimestre: '2º Trimestre', participationStatus: 'baixa', avgScore: 5.6 },
  { id: 't007', name: '7º B', schoolId: 's003', schoolName: 'EMEB Pedro Ribeiro', serie: '7º ano', turno: 'tarde', teacherId: 'p007', teacherName: 'Prof. Ricardo Alves', studentCount: 27, trimestre: '2º Trimestre', participationStatus: 'baixa', avgScore: 5.9 },
  { id: 't008', name: '6º A', schoolId: 's004', schoolName: 'EMEB João de Deus Barbosa', serie: '6º ano', turno: 'manhã', teacherId: 'p008', teacherName: 'Profa. Amanda Fonseca', studentCount: 30, trimestre: '2º Trimestre', participationStatus: 'alta', avgScore: 7.6 },
  { id: 't009', name: '8º B', schoolId: 's004', schoolName: 'EMEB João de Deus Barbosa', serie: '8º ano', turno: 'tarde', teacherId: 'p009', teacherName: 'Prof. Thiago Barros', studentCount: 28, trimestre: '2º Trimestre', participationStatus: 'alta', avgScore: 7.3 },
  { id: 't010', name: '5º B', schoolId: 's005', schoolName: 'EMEB Araci Cavalcante da Silva', serie: '5º ano', turno: 'manhã', teacherId: 'p010', teacherName: 'Profa. Patricia Gomes', studentCount: 24, trimestre: '2º Trimestre', participationStatus: 'media', avgScore: 6.6 },
];

// ── Estudantes ───────────────────────────────────────────────
export const students: Student[] = Array.from({ length: 20 }, (_, i) => {
  const names = [
    'Pedro Henrique Santos', 'Ana Clara Nascimento', 'João Pedro Ferreira', 'Maria Eduarda Melo',
    'Gabriel Silva Barbosa', 'Sophia Almeida Costa', 'Lucas Oliveira Souza', 'Isabela Gomes Araújo',
    'Matheus Lima Pereira', 'Larissa Cavalcante', 'Rafael Rodrigues Farias', 'Júlia Monteiro Lima',
    'Felipe Wanderley Neto', 'Letícia Tenório Brito', 'Bruno Lira Nascimento', 'Valentina Correia',
    'Guilherme Teixeira', 'Carolina Barros Vieira', 'Arthur Pinheiro Cruz', 'Giovanna Leite dos Santos',
  ];
  const turmaList = turmas.slice(0, 10);
  const turma = turmaList[i % 10];
  const scores = [
    { trimestre: '1º Trimestre', score: Math.round((5.0 + Math.random() * 3.5) * 10) / 10 },
    { trimestre: '2º Trimestre', score: Math.round((5.5 + Math.random() * 3.5) * 10) / 10 },
    { trimestre: '3º Trimestre', score: Math.round((6.0 + Math.random() * 3) * 10) / 10 },
  ];
  return {
    id: `st${String(i + 1).padStart(3, '0')}`,
    name: names[i],
    schoolId: turma.schoolId,
    schoolName: turma.schoolName,
    turmaId: turma.id,
    turmaName: turma.name,
    serie: turma.serie,
    matricula: `20250${String(1100 + i).padStart(4, '0')}`,
    age: 11 + (i % 5),
    status: i === 14 ? 'inativo' : 'ativo',
    scores,
    avgScore: Math.round((scores.reduce((a, b) => a + b.score, 0) / 3) * 10) / 10,
  } satisfies Student;
});

// ── Trimestres ───────────────────────────────────────────────
export const trimesters: Trimester[] = [
  { id: 'tr1', name: '1º Trimestre', startDate: '2025-02-03', endDate: '2025-04-30', status: 'encerrado', year: 2025 },
  { id: 'tr2', name: '2º Trimestre', startDate: '2025-05-05', endDate: '2025-07-31', status: 'ativo', year: 2025 },
  { id: 'tr3', name: '3º Trimestre', startDate: '2025-08-04', endDate: '2025-10-31', status: 'planejado', year: 2025 },
  { id: 'tr4', name: '4º Trimestre', startDate: '2025-11-03', endDate: '2025-12-12', status: 'planejado', year: 2025 },
];

// ── Avaliações ───────────────────────────────────────────────
export const evaluations: Evaluation[] = [
  {
    id: 'ev001', title: 'Diagnóstica de Criatividade e Inovação',
    serie: '6º ano', trimesterId: 'tr2', trimesterName: '2º Trimestre',
    competencia: 'Criatividade', habilidade: 'Geração de ideias',
    conteudo: 'Brainstorming e Design Thinking', totalPoints: 100,
    applicationDate: '2025-05-20', status: 'aplicada',
    respondents: 54, totalStudents: 54, avgScore: 72, // alinhado ao aprendizado adequado 56% Português
  },
  {
    id: 'ev002', title: 'Avaliação de Resolução de Problemas',
    serie: '7º ano', trimesterId: 'tr2', trimesterName: '2º Trimestre',
    competencia: 'Resolução de Problemas', habilidade: 'Análise situacional',
    conteudo: 'Situações-problema do cotidiano', totalPoints: 100,
    applicationDate: '2025-05-22', status: 'aplicada',
    respondents: 57, totalStudents: 57, avgScore: 68,
  },
  {
    id: 'ev003', title: 'Competências de Comunicação e Liderança',
    serie: '8º ano', trimesterId: 'tr2', trimesterName: '2º Trimestre',
    competencia: 'Comunicação', habilidade: 'Expressão oral e escrita',
    conteudo: 'Apresentação de projetos', totalPoints: 100,
    applicationDate: '2025-05-28', status: 'publicada',
    respondents: 45, totalStudents: 60, avgScore: 70,
  },
  {
    id: 'ev004', title: 'Educação Financeira Básica',
    serie: '9º ano', trimesterId: 'tr2', trimesterName: '2º Trimestre',
    competencia: 'Educação Financeira', habilidade: 'Planejamento financeiro',
    conteudo: 'Orçamento pessoal e familiar', totalPoints: 100,
    applicationDate: '2025-06-10', status: 'publicada',
    respondents: 0, totalStudents: 29, avgScore: 0,
  },
  {
    id: 'ev005', title: 'Diagnóstica 1 — Empreendedorismo e Projeto de Vida',
    serie: '5º ano', trimesterId: 'tr1', trimesterName: '1º Trimestre',
    competencia: 'Empreendedorismo', habilidade: 'Identificação de oportunidades',
    conteudo: 'Projeto de vida e protagonismo juvenil', totalPoints: 100,
    applicationDate: '2025-03-10', status: 'encerrada',
    respondents: 49, totalStudents: 49, avgScore: 65,
  },
];

// ── Avaliação Docente ─────────────────────────────────────────
export const teacherEvaluations: TeacherEvaluation[] = [
  {
    id: 'te001', teacherId: 'p001', teacherName: 'Prof. Lucas Andrade',
    schoolId: 's001', schoolName: 'EMEB Presidente Ernesto Geisel',
    trimesterId: 'tr2', trimesterName: '2º Trimestre',
    materialUse: 5, activityClarity: 4, studentEngagement: 5, trainingQuality: 4, supportReceived: 4,
    difficulties: 'Tempo reduzido para aplicação das atividades práticas no contraturno.',
    suggestions: 'Reduzir quantidade de questões por módulo e criar versão adaptada para turmas de EJA.',
    submittedAt: '2025-05-28',
  },
  {
    id: 'te002', teacherId: 'p002', teacherName: 'Profa. Beatriz Lima',
    schoolId: 's001', schoolName: 'EMEB Presidente Ernesto Geisel',
    trimesterId: 'tr2', trimesterName: '2º Trimestre',
    materialUse: 4, activityClarity: 5, studentEngagement: 4, trainingQuality: 5, supportReceived: 5,
    difficulties: 'Falta de recursos tecnológicos — apenas 4% das escolas do município têm laboratório de informática (dado INEP 2025).',
    suggestions: 'Criar atividades offline que não dependam de internet ou computadores.',
    submittedAt: '2025-05-30',
  },
  {
    id: 'te003', teacherId: 'p004', teacherName: 'Profa. Camila Torres',
    schoolId: 's002', schoolName: 'EMEB Coronel Adauto Gomes Barbosa',
    trimesterId: 'tr2', trimesterName: '2º Trimestre',
    materialUse: 3, activityClarity: 4, studentEngagement: 4, trainingQuality: 3, supportReceived: 3,
    difficulties: 'Material chegou com atraso. Ausência de quadra de esportes dificulta atividades práticas (apenas 20% das escolas têm quadra).',
    suggestions: 'Melhorar logística de entrega e criar roteiro de atividades adaptadas à infraestrutura real das escolas.',
    submittedAt: '2025-06-01',
  },
  {
    id: 'te004', teacherId: 'p008', teacherName: 'Profa. Amanda Fonseca',
    schoolId: 's004', schoolName: 'EMEB João de Deus Barbosa',
    trimesterId: 'tr2', trimesterName: '2º Trimestre',
    materialUse: 5, activityClarity: 5, studentEngagement: 5, trainingQuality: 5, supportReceived: 5,
    difficulties: 'Nenhuma dificuldade relevante.',
    suggestions: 'Ampliar o projeto para os 4º e 5º anos e conectar com a feira de ciências do município.',
    submittedAt: '2025-05-25',
  },
];

// ── Feedback Secretaria ───────────────────────────────────────
export const secretaryFeedbacks: SecretaryFeedback[] = [
  {
    id: 'sf001', userId: 'u002', userName: 'Sec. Mun. Francisco das Chagas',
    trimesterId: 'tr1', trimesterName: '1º Trimestre',
    generalRating: 4, perceivedImpact: 4,
    strengths: 'Engajamento dos estudantes e qualidade do material. Alinhamento com as ações do PAR (Plano de Ações Articuladas) municipal.',
    improvements: 'Ampliar participação das escolas rurais, especialmente a EMEB Pedro Ribeiro, que enfrenta dificuldades de acesso e conectividade.',
    alignment: 5,
    expectations: 'Esperamos que o projeto contribua para a elevação do IDEB dos anos finais (atualmente 5,4), alcançando a meta municipal de 6,0 até 2027.',
    decisions: 'Inclusão da EMEB Araci Cavalcante da Silva no 2º trimestre. Solicitação de formação específica sobre infraestrutura precária.',
    comment: 'O projeto Eleva+ chegou num momento importante para Limoeiro de Anadia. Com o IOEB municipal em 4,81, precisamos de iniciativas que transformem dados em ação pedagógica concreta.',
    submittedAt: '2025-05-05',
  },
];

// ── Formações ────────────────────────────────────────────────
export const trainings: Training[] = [
  {
    id: 'tr001', title: 'Metodologias Ativas no Empreendedorismo',
    date: '2025-03-15', hours: 8,
    trainer: 'Profa. Dra. Mariana Costa',
    schools: ['s001', 's002', 's003', 's004', 's005'],
    teacherCount: 42, topic: 'Design Thinking e PBL',
    rating: 4.7,
    observations: 'Excelente adesão. Realizada na sede da Secretaria Municipal de Educação de Limoeiro de Anadia.',
  },
  {
    id: 'tr002', title: 'Educação Financeira na Prática',
    date: '2025-04-10', hours: 4,
    trainer: 'Esp. Roberto Vieira',
    schools: ['s001', 's002', 's004'],
    teacherCount: 28, topic: 'Finanças pessoais, empreendedorismo e realidade local de AL',
    rating: 4.5,
  },
  {
    id: 'tr003', title: 'Avaliação por Competências — Alinhamento SAEB/IDEB',
    date: '2025-05-20', hours: 6,
    trainer: 'Profa. Dra. Mariana Costa',
    schools: ['s001', 's002', 's003', 's004', 's005'],
    teacherCount: 44,
    topic: 'Instrumentos avaliativos, portfólio e conexão com indicadores SAEB',
    rating: 4.8,
    observations: 'Foco especial na leitura dos dados de aprendizado adequado: Português 56%, Matemática 49% (Limoeiro de Anadia, 2023).',
  },
  {
    id: 'tr004', title: 'Projetos Empreendedores Interdisciplinares',
    date: '2025-06-18', hours: 8,
    trainer: 'Me. Felipe Nascimento',
    schools: ['s001', 's003', 's005'],
    teacherCount: 22,
    topic: 'Feira de Empreendedorismo e Startups Jr. — preparação para evento municipal',
    rating: 0,
    observations: 'Formação agendada. Articulação com a Secretaria de Educação para realização da I Feira Empreendedora de Limoeiro de Anadia.',
  },
];

// ── Evidências ───────────────────────────────────────────────
export const evidences: Evidence[] = [
  {
    id: 'ev1', title: 'Feira de Ideias — 6º A',
    description: 'Estudantes apresentaram projetos de solução para problemas reais de Limoeiro de Anadia: falta de saneamento básico, geração de renda no campo e turismo local.',
    type: 'foto', schoolId: 's001', schoolName: 'EMEB Presidente Ernesto Geisel',
    turmaId: 't001', turmaName: '6º A', teacherName: 'Prof. Lucas Andrade',
    trimesterId: 'tr2', competencia: 'Criatividade', createdAt: '2025-05-30',
  },
  {
    id: 'ev2', title: 'Simulação de Empresa — 8º A',
    description: 'Turma criou empresa fictícia de beneficiamento de mandioca — produto típico da região de Alagoas — com produto, pitch e plano financeiro básico.',
    type: 'projeto', schoolId: 's002', schoolName: 'EMEB Coronel Adauto Gomes Barbosa',
    turmaId: 't004', turmaName: '8º A', teacherName: 'Profa. Camila Torres',
    trimesterId: 'tr2', competencia: 'Empreendedorismo', createdAt: '2025-06-01',
  },
  {
    id: 'ev3', title: 'Relato: Superando a Baixa Conectividade',
    description: 'Na EMEB Pedro Ribeiro (zona rural, 0% de saneamento público), a professora adaptou todas as atividades para formato offline após ausência de internet por 3 semanas. Engajamento mantido em 100%.',
    type: 'relato', schoolId: 's003', schoolName: 'EMEB Pedro Ribeiro',
    turmaId: 't007', turmaName: '7º B', teacherName: 'Prof. Ricardo Alves',
    trimesterId: 'tr2', competencia: 'Colaboração', createdAt: '2025-05-27',
  },
];

// ── SWOT ─────────────────────────────────────────────────────
export const swotAnalyses: SwotAnalysis[] = [
  {
    id: 'sw001',
    trimesterId: 'tr2',
    trimesterName: '2º Trimestre',
    updatedAt: '2025-06-01',
    items: [
      { id: 'i1', category: 'forca', text: 'Alto engajamento dos estudantes nas atividades práticas' },
      { id: 'i2', category: 'forca', text: 'Material didático de alta qualidade e bem estruturado' },
      { id: 'i3', category: 'forca', text: 'Apoio institucional da Secretaria Municipal de Educação' },
      { id: 'i4', category: 'forca', text: 'IDEB de anos iniciais acima da média estadual (6,6 — AL: 5,2)' },
      { id: 'i5', category: 'forca', text: '100% das escolas com energia elétrica e alimentação fornecida (Censo 2025)' },
      { id: 'i6', category: 'fraqueza', text: 'Baixa participação nas escolas rurais (ex.: EMEB Pedro Ribeiro, 72%)' },
      { id: 'i7', category: 'fraqueza', text: 'Apenas 4% das escolas têm laboratório de informática (Censo INEP 2025)' },
      { id: 'i8', category: 'fraqueza', text: '0% de esgotamento sanitário público nas escolas' },
      { id: 'i9', category: 'fraqueza', text: 'IDEB de anos finais abaixo da meta nacional (5,4 vs. meta 6,0)' },
      { id: 'i10', category: 'oportunidade', text: 'I Feira Empreendedora de Limoeiro de Anadia planejada para outubro' },
      { id: 'i11', category: 'oportunidade', text: 'Parceria com produtores rurais locais para projetos de agronegócio empreendedor' },
      { id: 'i12', category: 'oportunidade', text: 'Articulação com SEBRAE/AL para mentorias em empreendedorismo juvenil' },
      { id: 'i13', category: 'oportunidade', text: 'Projeto alinhado ao PAR municipal e às metas do FUNDEB complementar (VAAR)' },
      { id: 'i14', category: 'ameaca', text: 'Baixa conectividade — especialmente em zona rural (0% de esgoto; 92% banda larga urbana)' },
      { id: 'i15', category: 'ameaca', text: 'Distorção idade-série ainda elevada em anos finais (dados INEP 2025)' },
      { id: 'i16', category: 'ameaca', text: 'Rotatividade docente em escolas com menor infraestrutura' },
    ],
  },
];

// ── Metas SMART ──────────────────────────────────────────────
export const smartGoals: SmartGoal[] = [
  {
    id: 'sg001',
    title: 'Elevar desempenho na EMEB Pedro Ribeiro',
    schoolId: 's003', schoolName: 'EMEB Pedro Ribeiro',
    indicator: 'Média de desempenho nas avaliações Eleva+',
    description: 'Elevar a média da escola de 5,8 para 6,5 até o final do 3º trimestre, com foco em resolução de problemas e comunicação (competências do SAEB).',
    initialValue: 5.8, targetValue: 6.5, currentValue: 6.1,
    deadline: '2025-10-31', responsible: 'Carla Mendes Ferreira',
    status: 'em_andamento',
    evidences: ['Plano de tutoria iniciado', 'Adaptação offline das atividades'],
    observations: 'Escola rural — sem laboratório de informática. Todas as atividades adaptadas para modo presencial/offline.',
  },
  {
    id: 'sg002',
    title: 'Aumentar participação docente para 90%',
    indicator: 'Taxa de resposta ao formulário docente',
    description: 'Atingir 90% de participação dos professores nos formulários de avaliação até o 3º trimestre, cobrindo todas as 5 escolas do projeto.',
    initialValue: 68, targetValue: 90, currentValue: 78,
    deadline: '2025-10-31', responsible: 'Profa. Dra. Mariana Costa',
    status: 'em_andamento', evidences: [],
  },
  {
    id: 'sg003',
    title: 'Evidências pedagógicas: 3 por escola por trimestre',
    indicator: 'Número de evidências registradas por escola',
    description: 'Garantir ao menos 3 evidências pedagógicas registradas por escola por trimestre — conectando o Eleva+ ao portfólio avaliativo das escolas.',
    initialValue: 1, targetValue: 3, currentValue: 3,
    deadline: '2025-07-31', responsible: 'Coordenadores escolares',
    status: 'concluida',
    evidences: ['Feira de Ideias', 'Simulação de Empresa', 'Relato — zona rural'],
  },
  {
    id: 'sg004',
    title: 'Satisfação docente ≥ 4,5 na EMEB Coronel Adauto Gomes Barbosa',
    schoolId: 's002', schoolName: 'EMEB Coronel Adauto Gomes Barbosa',
    indicator: 'Nota média de satisfação docente (escala 1–5)',
    description: 'Elevar satisfação docente de 3,5 para 4,5 com melhoria na logística de entrega do material e capacitação para infraestrutura precária.',
    initialValue: 3.5, targetValue: 4.5, currentValue: 3.8,
    deadline: '2025-07-31', responsible: 'Roberto Campos dos Santos',
    status: 'em_andamento', evidences: [],
    observations: 'Prazo de entrega do material corrigido. Formação extra sobre atividades sem laboratório de informática agendada.',
  },
  {
    id: 'sg005',
    title: 'Contribuir para meta IDEB anos finais',
    indicator: 'IDEB anos finais (Limoeiro de Anadia)',
    description: 'Contribuir, via desenvolvimento de competências de leitura e raciocínio, para a elevação do IDEB de anos finais de 5,4 para 6,0 até 2027 (meta municipal).',
    initialValue: 5.4, targetValue: 6.0, currentValue: 5.4,
    deadline: '2027-12-31', responsible: 'Sec. Mun. Francisco das Chagas',
    status: 'planejada', evidences: [],
    observations: 'Meta de longo prazo alinhada ao PAR. Indicador oficial aferido pelo INEP a cada 2 anos.',
  },
];

// ── Plano de Ação ────────────────────────────────────────────
export const actionPlans: ActionPlan[] = [
  {
    id: 'ap001',
    problem: 'Baixa participação na EMEB Pedro Ribeiro (zona rural)',
    schoolId: 's003', schoolName: 'EMEB Pedro Ribeiro',
    cause: 'Localização rural com acesso limitado, falta de conectividade (0% esgoto, banda larga instável) e sobrecarga docente.',
    action: 'Oferecer formação extra presencial de 4h na escola, designar mentor de apoio e criar versão offline completa do material didático em formato impresso.',
    responsible: 'Profa. Dra. Mariana Costa',
    deadline: '2025-07-15',
    resources: 'Formador + transporte + material impresso (verba FUNDEB complementar)',
    successIndicator: 'Participação docente ≥ 85% e média dos estudantes ≥ 6,0 no 3º trimestre',
    status: 'em_andamento',
    observations: 'Formação presencial agendada para 25/06. Impressão do material em andamento.',
  },
  {
    id: 'ap002',
    problem: 'Logística de entrega do material didático com atraso',
    cause: 'Falha na logística com a gráfica — material chegou fora do prazo nas escolas.',
    action: 'Renegociar contrato com gráfica e estabelecer prazo de entrega 15 dias antes do início de cada trimestre.',
    responsible: 'Coord. Administrativa Acelera+',
    deadline: '2025-06-30',
    resources: 'Contrato e gestão logística',
    successIndicator: 'Material entregue até o dia 1 de cada trimestre para todas as 5 escolas',
    status: 'concluido',
  },
  {
    id: 'ap003',
    problem: 'Ausência de laboratório de informática em 96% das escolas',
    cause: 'Infraestrutura tecnológica precária — dado do Censo INEP 2025: apenas 4% das escolas de Limoeiro de Anadia têm laboratório de informática.',
    action: 'Desenvolver roteiro de atividades analógicas e criar "Kit Empreendedor" físico (cartões, dados, formulários impressos) que substitua os recursos digitais.',
    responsible: 'Equipe Pedagógica Eleva+',
    deadline: '2025-08-01',
    resources: 'Equipe de design pedagógico + impressão',
    successIndicator: 'Kit disponível em todas as 5 escolas antes do 3º trimestre',
    status: 'pendente',
  },
  {
    id: 'ap004',
    problem: 'IDEB de anos finais abaixo da meta (5,4 vs. 6,0)',
    cause: 'Distorção idade-série, abandono escolar residual e baixo desempenho em leitura e matemática nos anos finais.',
    action: 'Alinhar as atividades de empreendedorismo com as habilidades do SAEB (interpretação de texto, raciocínio lógico aplicado) para potencializar o impacto nas avaliações externas.',
    responsible: 'Coordenação Pedagógica Municipal',
    deadline: '2025-10-31',
    resources: 'Reuniões de alinhamento + material complementar SAEB',
    successIndicator: 'Melhora de 0,3 pontos no IDEB de anos finais no ciclo 2025',
    status: 'em_andamento',
  },
];

// ── Usuários ─────────────────────────────────────────────────
export const users: User[] = [
  {
    id: 'u001', name: 'Ana Paula Rodrigues',
    email: 'ana.rodrigues@elevaplus.edu.br',
    phone: '(82) 98765-4321',
    role: 'super_admin', municipio: 'Limoeiro de Anadia',
    status: 'ativo', lastAccess: '2025-06-04T09:30:00',
  },
  {
    id: 'u002', name: 'Sec. Mun. Francisco das Chagas',
    email: 'secretario@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-0001',
    role: 'secretaria', municipio: 'Limoeiro de Anadia',
    status: 'ativo', lastAccess: '2025-06-03T14:20:00',
  },
  {
    id: 'u003', name: 'Profa. Dra. Mariana Costa',
    email: 'mariana.costa@elevaplus.edu.br',
    phone: '(82) 99887-6543',
    role: 'admin_eleva', municipio: 'Limoeiro de Anadia',
    status: 'ativo', lastAccess: '2025-06-04T08:15:00',
  },
  {
    id: 'u004', name: 'Francisca Nunes Cavalcante',
    email: 'francisca.nunes@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1201',
    role: 'gestor_escolar', schoolId: 's001', municipio: 'Limoeiro de Anadia',
    status: 'ativo', lastAccess: '2025-06-02T10:00:00',
  },
  {
    id: 'u005', name: 'Roberto Campos dos Santos',
    email: 'roberto.campos@semed.limoeiro.al.gov.br',
    phone: '(82) 3533-1202',
    role: 'gestor_escolar', schoolId: 's002', municipio: 'Limoeiro de Anadia',
    status: 'ativo', lastAccess: '2025-06-01T16:45:00',
  },
  {
    id: 'u006', name: 'Prof. Lucas Andrade',
    email: 'lucas.andrade@semed.limoeiro.al.gov.br',
    phone: '(82) 99123-4567',
    role: 'professor', schoolId: 's001', municipio: 'Limoeiro de Anadia',
    status: 'ativo', lastAccess: '2025-06-04T07:30:00',
  },
  {
    id: 'u007', name: 'Profa. Amanda Fonseca',
    email: 'amanda.fonseca@semed.limoeiro.al.gov.br',
    phone: '(82) 99234-5678',
    role: 'professor', schoolId: 's004', municipio: 'Limoeiro de Anadia',
    status: 'ativo', lastAccess: '2025-06-03T11:00:00',
  },
  {
    id: 'u008', name: 'Obs. Regional FNDE/AL',
    email: 'observador@fnde.gov.br',
    role: 'visualizador', municipio: 'Limoeiro de Anadia',
    status: 'ativo', lastAccess: '2025-05-20T09:00:00',
  },
];

// ── Dashboard Stats ──────────────────────────────────────────
// Baseado nos dados reais do Censo INEP 2025 e SAEB/IDEB 2023
export const dashboardStats: DashboardStats = {
  totalSchools: 5,          // escolas no projeto (total rede: 25)
  totalClasses: 40,         // estimativa para as 5 escolas
  totalStudents: 1056,      // soma das 5 escolas participantes
  totalTeachers: 57,        // soma de professores das 5 escolas
  evaluationResponseRate: 86,
  avgStudentScore: 6.7,     // média entre IDEB anos iniciais (6.6) e anos finais (5.4) + impacto Eleva+
  projectExecutionLevel: 79,
  teacherTrainingParticipation: 91,
  teacherSatisfaction: 4.1,
  secretarySatisfaction: 4.0,
  elevaIndex: 76,
  elevaIndexLevel: 'bom',
};

// ── Dados para Gráficos ──────────────────────────────────────
// Pontuações baseadas no IDEB e aprendizado adequado de Limoeiro de Anadia
export const scoreBySchool: ChartDataPoint[] = [
  { label: 'E. Geisel', value: 7.2, color: '#2E8C99' },
  { label: 'Cel. Adauto', value: 7.5, color: '#2E8C99' },
  { label: 'P. Ribeiro', value: 5.8, color: '#F48B1B' },
  { label: 'J. de Deus', value: 6.8, color: '#2E8C99' },
  { label: 'Araci Cav.', value: 6.5, color: '#2E8C99' },
];

export const participationBySchool: ChartDataPoint[] = [
  { label: 'E. Geisel', value: 94, color: '#2E8C99' },
  { label: 'Cel. Adauto', value: 96, color: '#2E8C99' },
  { label: 'P. Ribeiro', value: 72, color: '#F48B1B' },
  { label: 'J. de Deus', value: 88, color: '#2E8C99' },
  { label: 'Araci Cav.', value: 81, color: '#2E8C99' },
];

// Progressão trimestral — partindo do IDEB real (anos finais 5.4) com crescimento
export const scoreByTrimester: ChartDataPoint[] = [
  { label: '1º Trim.', value: 6.2, color: '#2E8C99' },
  { label: '2º Trim.', value: 6.7, color: '#F48B1B' },
  { label: '3º Trim.', value: 0, color: '#E8EAED' },
  { label: '4º Trim.', value: 0, color: '#E8EAED' },
];

// Uso do material — dado docente
export const materialUsageData: ChartDataPoint[] = [
  { label: 'Usa sempre', value: 49, color: '#2E8C99' },
  { label: 'Usa frequente', value: 33, color: '#4BAAB6' },
  { label: 'Usa às vezes', value: 12, color: '#F48B1B' },
  { label: 'Pouco uso', value: 6, color: '#E30613' },
];

// Aprendizado adequado por competência
// Referência: aprendizado adequado 2023 — Português 56%, Matemática 49%
export const competenciasData: ChartDataPoint[] = [
  { label: 'Criatividade', value: 72 },
  { label: 'Resolução', value: 68 },
  { label: 'Comunicação', value: 70 },
  { label: 'Colaboração', value: 75 },
  { label: 'Liderança', value: 61 },
  { label: 'Ed. Financeira', value: 64 },
];
